inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Bundler/DuplicatedGem:
  Enabled: false

Layout/AlignHash:
  EnforcedHashRocketStyle: table

Layout/IndentHeredoc:
  Enabled: false

Layout/TrailingWhitespace:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'

Metrics/LineLength:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'Gemfile'
